FROM hugomods/hugo:go-git as build
ENV BUILD_ID 2024-12-20-080400

# Copy your static files
COPY src .

# Build the Hugo site
RUN rm -rf public \
    && hugo \
    && ls -la public \
    && cp public/images/favicon.ico public/favicon.ico

# Create a new stage with the Nginx Alpine image
FROM nginx:alpine

# Copy the static website files generated by Hugo from the build stage to the Nginx container
COPY --from=build /src/public /site
ADD nginx.conf /etc/nginx/templates/default.conf.template

ENV NGINX_PORT 5005
ENV NGINX_HOST localhost

EXPOSE $NGINX_PORT
