server {
    listen ${NGINX_PORT};
    server_name ${NGINX_HOST};

    root /site;
    index index.html index.htm;

    location /healthz {
        access_log on;
        return 200 '{"status": "ok";}';
        add_header Content-Type application/json;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    #location ~* ^/([^/]+) {
    #    index index.html index.htm;
    #    error_page 404 = @error;
    #}

    error_page 404 /404.html;
    location @error {
        try_files /$1/404.html /404.html =404;
    }
}
